package com.example.ui.screens

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.widget.Toast
import androidx.compose.animation.*
import androidx.compose.animation.core.*
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.components.AnimatedEntrance
import com.example.ui.components.glassmorphic
import com.example.ui.viewmodel.PortfolioViewModel
import com.example.ui.viewmodel.PortMapping
import kotlin.random.Random

@OptIn(ExperimentalLayoutApi::class)
@Composable
fun ContactScreen(
    viewModel: PortfolioViewModel,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val portMappings by viewModel.portMappings.collectAsState()
    val sshKeyGenerated by viewModel.sshKeyGenerated.collectAsState()

    val accentColorState by viewModel.accentColor.collectAsState()
    val themeAccent = Color(accentColorState.hex)

    // Form states for port adder
    var inputPort by remember { mutableStateOf("") }
    var inputServiceName by remember { mutableStateOf("") }

    // Selected port for QR preview
    var selectedMappingForQr by remember { mutableStateOf<PortMapping?>(null) }

    // Initialize first port mapping as selected on startup
    LaunchedEffect(portMappings) {
        if (selectedMappingForQr == null && portMappings.isNotEmpty()) {
            selectedMappingForQr = portMappings.first()
        }
    }

    val scrollState = rememberScrollState()

    Column(
        modifier = modifier
            .fillMaxSize()
            .verticalScroll(scrollState)
            .padding(14.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        // App header
        AnimatedEntrance(delayMillis = 100) {
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .glassmorphic(MaterialTheme.colorScheme.surface.copy(alpha = 0.5f), cornerRadius = 14.dp)
                    .padding(horizontal = 12.dp, vertical = 10.dp),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Column {
                    Text(
                        "Ports & Gateway",
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.ExtraBold,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                    Text(
                        "Manage SSH key chains and localhost server mappings",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }

                Box(
                    modifier = Modifier
                        .size(36.dp)
                        .background(themeAccent.copy(alpha = 0.15f), CircleShape),
                    contentAlignment = Alignment.Center
                ) {
                    Icon(Icons.Default.Dns, "Network Gateway icon", tint = themeAccent, modifier = Modifier.size(18.dp))
                }
            }
        }

        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            // Left Panel: Ports Forwarding Manager list
            Card(
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface.copy(alpha = 0.5f)),
                modifier = Modifier
                    .weight(1.1f)
                    .glassmorphic(MaterialTheme.colorScheme.surface, borderColor = themeAccent.copy(alpha = 0.1f), cornerRadius = 16.dp)
                    .testTag("ports_manager_panel")
            ) {
                Column(modifier = Modifier.padding(12.dp)) {
                    Text(
                        "ACTIVE LOCAL PORT MAPPINGS",
                        style = MaterialTheme.typography.labelSmall,
                        fontWeight = FontWeight.Bold,
                        color = themeAccent,
                        modifier = Modifier.padding(bottom = 8.dp)
                    )

                    Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                        portMappings.forEach { mapping ->
                            val isSelected = selectedMappingForQr?.id == mapping.id
                            val itemBg = if (isSelected) themeAccent.copy(alpha = 0.12f) else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f)
                            val itemBorder = if (isSelected) themeAccent else Color.Transparent

                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .clip(RoundedCornerShape(8.dp))
                                    .background(itemBg)
                                    .border(1.dp, itemBorder, RoundedCornerShape(8.dp))
                                    .clickable { selectedMappingForQr = mapping }
                                    .padding(8.dp),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Box(
                                        modifier = Modifier
                                            .size(24.dp)
                                            .background(themeAccent.copy(alpha = 0.2f), CircleShape),
                                        contentAlignment = Alignment.Center
                                    ) {
                                        Text(
                                            mapping.port.toString().takeLast(2),
                                            fontSize = 9.sp,
                                            fontWeight = FontWeight.Black,
                                            color = themeAccent
                                        )
                                    }
                                    Spacer(modifier = Modifier.width(10.dp))
                                    Column {
                                        Text(
                                            "localhost:${mapping.port}",
                                            style = MaterialTheme.typography.labelMedium,
                                            fontWeight = FontWeight.Bold,
                                            fontFamily = FontFamily.Monospace
                                        )
                                        Text(
                                            mapping.serviceName,
                                            style = MaterialTheme.typography.labelSmall,
                                            color = MaterialTheme.colorScheme.onSurfaceVariant
                                        )
                                    }
                                }

                                IconButton(
                                    onClick = { viewModel.removePortMapping(mapping.id) },
                                    modifier = Modifier.size(24.dp)
                                ) {
                                    Icon(Icons.Default.Close, "Delete Port", tint = Color.Red.copy(alpha = 0.7f), modifier = Modifier.size(14.dp))
                                }
                            }
                        }
                    }

                    Spacer(modifier = Modifier.height(14.dp))

                    // Inner form to add new ports
                    Text("ESTABLISH NEW PORT FORWARD", style = MaterialTheme.typography.labelSmall, fontWeight = FontWeight.Bold, color = themeAccent)
                    Spacer(modifier = Modifier.height(8.dp))

                    OutlinedTextField(
                        value = inputPort,
                        onValueChange = { inputPort = it },
                        label = { Text("Port Number", fontSize = 11.sp) },
                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                        singleLine = true,
                        colors = OutlinedTextFieldDefaults.colors(
                            focusedBorderColor = themeAccent,
                            focusedLabelColor = themeAccent
                        ),
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(50.dp)
                            .testTag("port_number_input")
                    )

                    Spacer(modifier = Modifier.height(8.dp))

                    OutlinedTextField(
                        value = inputServiceName,
                        onValueChange = { inputServiceName = it },
                        label = { Text("Target Endpoint Name", fontSize = 11.sp) },
                        singleLine = true,
                        colors = OutlinedTextFieldDefaults.colors(
                            focusedBorderColor = themeAccent,
                            focusedLabelColor = themeAccent
                        ),
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(50.dp)
                            .testTag("port_name_input")
                    )

                    Spacer(modifier = Modifier.height(12.dp))

                    Button(
                        onClick = {
                            val portInt = inputPort.toIntOrNull() ?: 0
                            if (portInt > 0) {
                                viewModel.addNewPortMapping(portInt, inputServiceName.ifEmpty { "Custom Service" })
                                inputPort = ""
                                inputServiceName = ""
                            }
                        },
                        colors = ButtonDefaults.buttonColors(containerColor = themeAccent),
                        shape = RoundedCornerShape(10.dp),
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(38.dp)
                            .testTag("btn_submit_port_forward")
                    ) {
                        Text("Establish Tunnel Map", fontSize = 12.sp, color = Color.White, fontWeight = FontWeight.Bold)
                    }
                }
            }

            // Right Panel: Host Server QR scan code simulator preview
            Card(
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface.copy(alpha = 0.5f)),
                modifier = Modifier
                    .weight(0.9f)
                    .glassmorphic(MaterialTheme.colorScheme.surface, borderColor = themeAccent.copy(alpha = 0.1f), cornerRadius = 16.dp)
                    .testTag("qr_preview_panel")
            ) {
                Column(
                    modifier = Modifier.padding(10.dp),
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.Center
                ) {
                    Text(
                        "WEB PREVIEW QR",
                        style = MaterialTheme.typography.labelSmall,
                        fontWeight = FontWeight.Bold,
                        color = themeAccent,
                        modifier = Modifier.align(Alignment.Start)
                    )
                    Spacer(modifier = Modifier.height(2.dp))
                    Text(
                        selectedMappingForQr?.let { "Scan to view port ${it.port}" } ?: "No active server port",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        modifier = Modifier.align(Alignment.Start)
                    )

                    Spacer(modifier = Modifier.height(14.dp))

                    // Drawn procedural vector QR code inside compose Canvas
                    Box(
                        modifier = Modifier
                            .size(130.dp)
                            .background(Color.White, RoundedCornerShape(12.dp))
                            .border(2.dp, themeAccent, RoundedCornerShape(12.dp))
                            .padding(10.dp),
                        contentAlignment = Alignment.Center
                    ) {
                        QrCodeCanvasSim(accentColor = themeAccent, serviceSeed = selectedMappingForQr?.serviceName ?: "empty")
                    }

                    Spacer(modifier = Modifier.height(14.dp))

                    Button(
                        onClick = {
                            selectedMappingForQr?.let {
                                val urlLink = "https://localhost-${it.port}.tunnel.neoterm.dev/"
                                val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
                                val clip = ClipData.newPlainText("neoterm_tunnel_link", urlLink)
                                clipboard.setPrimaryClip(clip)
                                Toast.makeText(context, "Copied tunnel link to clipboard!", Toast.LENGTH_SHORT).show()
                            }
                        },
                        colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.surfaceVariant),
                        shape = RoundedCornerShape(10.dp),
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(36.dp)
                            .testTag("btn_copy_tunnel_link")
                    ) {
                        Icon(Icons.Default.ContentCopy, null, tint = themeAccent, modifier = Modifier.size(14.dp))
                        Spacer(modifier = Modifier.width(6.dp))
                        Text("Copy Link", fontSize = 11.sp, color = themeAccent, fontWeight = FontWeight.Bold)
                    }
                }
            }
        }

        // Section 2: SSH Key Manager section with live .ssh file creators
        AnimatedEntrance(delayMillis = 200) {
            Card(
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface.copy(alpha = 0.5f)),
                modifier = Modifier
                    .fillMaxWidth()
                    .glassmorphic(MaterialTheme.colorScheme.surface, borderColor = themeAccent.copy(alpha = 0.12f), cornerRadius = 16.dp)
                    .testTag("ssh_key_card_block")
            ) {
                Column(modifier = Modifier.padding(14.dp)) {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Box(
                                modifier = Modifier
                                    .size(36.dp)
                                    .background(themeAccent.copy(alpha = 0.15f), RoundedCornerShape(10.dp)),
                                contentAlignment = Alignment.Center
                            ) {
                                Icon(Icons.Default.Key, "Key details icon", tint = themeAccent, modifier = Modifier.size(18.dp))
                            }
                            Spacer(modifier = Modifier.width(10.dp))
                            Column {
                                Text("SSH Key Manager (RSA / Ed25519)", style = MaterialTheme.typography.labelLarge, fontWeight = FontWeight.Bold)
                                Text("GitHub authentication credentials", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                            }
                        }

                        // Status Badge
                        Box(
                            modifier = Modifier
                                .background(
                                    if (sshKeyGenerated) Color.Green.copy(alpha = 0.12f) else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.6f),
                                    RoundedCornerShape(6.dp)
                                )
                                .padding(horizontal = 6.dp, vertical = 2.dp)
                        ) {
                            Text(
                                if (sshKeyGenerated) "SECURED" else "NOT CREATED",
                                fontSize = 10.sp,
                                fontWeight = FontWeight.Bold,
                                color = if (sshKeyGenerated) Color.Green else MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    }

                    Spacer(modifier = Modifier.height(14.dp))

                    if (!sshKeyGenerated) {
                        Text(
                            text = "No public SSH key detected in your profile context. To synchronize files with remote GitHub hubs, trigger key pair generation.",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            lineHeight = 16.sp,
                            modifier = Modifier.padding(bottom = 12.dp)
                        )

                        Button(
                            onClick = {
                                viewModel.addNewTerminalTab("Local Shell")
                                viewModel.removeTab(viewModel.terminalTabs.value.last().id)
                                viewModel.setCommandInput(viewModel.terminalTabs.value.first().id, "ssh-keygen")
                                viewModel.runTerminalCommand(viewModel.terminalTabs.value.first().id)
                            },
                            colors = ButtonDefaults.buttonColors(containerColor = themeAccent),
                            shape = RoundedCornerShape(10.dp),
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(40.dp)
                                .testTag("btn_generate_ssh_triggers")
                        ) {
                            Text("🔑 Generate Secure Keys", fontSize = 12.sp, color = Color.White, fontWeight = FontWeight.Bold)
                        }
                    } else {
                        Column {
                            Text(
                                text = "Public RSA Key Cached:",
                                style = MaterialTheme.typography.labelSmall,
                                fontWeight = FontWeight.Bold,
                                color = themeAccent
                            )
                            Spacer(modifier = Modifier.height(6.dp))

                            Box(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .background(Color.Black.copy(alpha = 0.5f))
                                    .border(1.dp, MaterialTheme.colorScheme.outline.copy(alpha = 0.3f), RoundedCornerShape(6.dp))
                                    .padding(8.dp)
                            ) {
                                Text(
                                    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSBLpDxSMYG9G9Q3X4U... neoterm@android",
                                    fontSize = 11.sp,
                                    fontFamily = FontFamily.Monospace,
                                    color = Color.Green,
                                    maxLines = 2
                                )
                            }

                            Spacer(modifier = Modifier.height(12.dp))

                            Button(
                                onClick = {
                                    val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
                                    val clip = ClipData.newPlainText("ssh_rsa_key_neoterm", "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSBLpDxSMYG9G9Q3X4U... neoterm@android")
                                    clipboard.setPrimaryClip(clip)
                                    Toast.makeText(context, "Public key copied!", Toast.LENGTH_SHORT).show()
                                },
                                colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.surfaceVariant),
                                shape = RoundedCornerShape(10.dp),
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(38.dp)
                                    .testTag("btn_copy_ssh_public_key")
                            ) {
                                Text("Copy public key to clipboard", fontSize = 12.sp, color = themeAccent, fontWeight = FontWeight.Bold)
                            }
                        }
                    }
                }
            }
        }
    }
}

@Composable
fun QrCodeCanvasSim(accentColor: Color, serviceSeed: String) {
    Canvas(modifier = Modifier.fillMaxSize()) {
        val countGrid = 11
        val squareWidthVal = size.width / countGrid
        val squareHeightVal = size.height / countGrid

        // Render QR corner locator patterns
        val cornerLocators = listOf(
            Offset(0f, 0f),
            Offset(size.width - 3 * squareWidthVal, 0f),
            Offset(0f, size.height - 3 * squareHeightVal)
        )

        cornerLocators.forEach { loc ->
            drawRect(
                color = Color.Black,
                style = androidx.compose.ui.graphics.drawscope.Fill,
                size = Size(squareWidthVal * 3, squareHeightVal * 3),
                topLeft = loc
            )
            drawRect(
                color = Color.White,
                style = androidx.compose.ui.graphics.drawscope.Fill,
                size = Size(squareWidthVal * 1.8f, squareHeightVal * 1.8f),
                topLeft = Offset(loc.x + squareWidthVal * 0.6f, loc.y + squareHeightVal * 0.6f)
            )
            drawRect(
                color = Color.Black,
                style = androidx.compose.ui.graphics.drawscope.Fill,
                size = Size(squareWidthVal, squareHeightVal),
                topLeft = Offset(loc.x + squareWidthVal, loc.y + squareHeightVal)
            )
        }

        // Draw simulated random QR matrix code dots
        val rand = Random(serviceSeed.hashCode())
        for (row in 0 until countGrid) {
            for (col in 0 until countGrid) {
                // Avoid drawing over outer corner patterns
                if ((row < 3 && col < 3) || (row < 3 && col > countGrid - 4) || (row > countGrid - 4 && col < 3)) {
                    continue
                }

                if (rand.nextBoolean()) {
                    drawRect(
                        color = if (rand.nextInt(10) > 7) accentColor else Color.Black,
                        topLeft = Offset(col * squareWidthVal, row * squareHeightVal),
                        size = Size(squareWidthVal * 0.95f, squareHeightVal * 0.95f)
                    )
                }
            }
        }
    }
}
